import Head from 'next/head';
import styles from "../styles/home.module.scss";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>صفحه اصلی </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
          <div className={styles.header}>
              <h1> صفحه اصلی جستجوی کاربر </h1>
          </div>
         <div className={styles.btn_box}>
             <Link href="/defunkt">
                 <button> صفحه جستجوی کاربر </button>
             </Link>
             <Link href="/most-popular">
                 <button> لیست ریپو ها با بیشترین ستاره </button>
             </Link>
         </div>
      </main>
    </>
  )
}
