import Head from 'next/head';
import styles from "../styles/home.module.scss";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>صفحه اصلی </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
          <Link href="/defunkt">
              <button> صفحه جستجوی کاربر </button>
          </Link>
      </main>
    </>
  )
}
